# fly.toml app configuration file generated for big-ideal-api on 2024-05-04T11:38:59+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'big-ideal-api'
primary_region = 'nrt'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
